name: Issues Event Test

on:
  issues:
    types: [opened, reopened, edited, closed]

jobs:
    issues-event-tests:
        runs-on: [self-hosted, linux, x64]
        steps:
        - name: Echo runner name
          run: |
            echo "Hello, world"
