name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: [self-hosted, linux, x64]
    steps:
#      - uses: actions/checkout@v4.1.1
#      - name: Remove Android SDK
#        run: sudo rm -rf /usr/local/lib/android
#      - name: Setup operator environment
#        uses: charmed-kubernetes/actions-operator@main
#        with:
#          provider: lxd
#          microk8s-addons: "dns ingress rbac storage"
#          channel: latest/stable
#          juju-channel: 3.2
#      - run: sleep 7200
      - run: |
          sudo snap install openstack --channel 2023.1
          sunbeam prepare-node-script | bash -x
          sudo -g snap_daemon sunbeam cluster bootstrap --accept-defaults
          sudo -g snap_daemon sunbeam configure --accept-defaults --openrc demo-openrc
          sudo -g snap_daemon sunbeam openrc > admin-openrc
          . admin-openrc
          openstack user list
