name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Fail
        run: |
            echo "This job should fail"
            exit 1
