name: Push Event Tests

on:
  push:

jobs:
    test:
#        runs-on: [self-hosted, linux, x64, two-xlarge]
        runs-on: ubuntu-latest
        steps:
#        - name: Get node info
#          run: |
#              lscpu
#              free -g
#              df -h
#              cat /etc/environment
#              env
        - name: Setup operator environment
          uses: charmed-kubernetes/actions-operator@main
          with:
            channel: 1.26-strict/stable
            provider: microk8s
            juju-channel: 3.2
            microk8s-addons: "dns ingress hostpath-storage"
        - run: |
            retry() {
                local command="$1"
                local wait_message="$2"
                local max_try="$3"

                local attempt=0

                while ! $command
                do
                    attempt=$((attempt + 1))
                    if [[ attempt -ge $max_try ]]; then
                        return
                    fi

                    juju models || echo "Failed to list models"
                    juju controllers || echo "Failed to list controllers"
                    juju switch openstack || echo "Failed to switch to openstack"
                    juju status --color || echo "Failed to get status"
                    echo "$wait_message"
                    sleep 10
                done
            }
#            head -n  1 /etc/environment > temp && sudo mv temp /etc/environment
#            unset HTTP_PROXY HTTPS_PROXY NO_PROXY http_proxy https_proxy no_proxy
            sudo snap remove kubectl # microk8s charm tries to make an alias and errors otherwise
            sudo snap install openstack --channel 2023.1 --devmode
            sunbeam prepare-node-script | bash -x
            sleep 10
            retry 'sudo -g snap_daemon sunbeam cluster bootstrap --accept-defaults' 'Waiting for cluster bootstrap to complete' 3
            sudo -g snap_daemon sunbeam openrc > admin-openrc
            . admin-openrc
            openstack user list
