name: Push Event Tests

on:
  push:

jobs:
  push-tests:
    runs-on: [self-hosted, linux, x64, app1/0-flavor]
    steps:
      - name: Echo runner name
        run: |
          echo "Hello, world again and again and again"
