name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: [self-hosted, linux, cos-test]
    steps:
      - name: Echo runner name
        run: |
          ls /home/ubuntu/metrics-exchange
          cat /home/ubuntu/metrics-exchange/pre-job-metrics.json || true
          cat /home/ubuntu/metrics-exchange/post-job-metrics.json || true
          cat /home/ubuntu/actions-runner/pre-job.sh || true
