name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Echo default ip
        run: |
              t=$(ip route show 0.0.0.0/0 | grep -oP 'via \K\S+')
              echo $t
              x=$(ip route get $t | grep -oP 'src \K\S+')
              echo $x

