name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
