name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo snap install openstack --channel 2023.1
          sunbeam prepare-node-script | bash -x
          sudo -g snap_daemon sunbeam cluster bootstrap --accept-defaults
          sudo -g snap_daemon sunbeam configure --accept-defaults --openrc demo-openrc
          sudo -g snap_daemon sunbeam openrc > admin-openrc
          . admin-openrc
          openstack user list