name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: [self-hosted]
    steps:
      - name: hello world
        run: echo "Hello, world"
      - name: provoke a oom by allocating a lot of memory
        run: python3 -c "a = '1'*1000000000; print(a)"