name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: systemctl status
        run: |
          systemctl status
          systemctl status unattended-upgrades || echo "not available"