name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          microk8s-addons: dns ingress rbac storage
          channel: 1.29-strict/stable
          juju-channel: 3.1/stable
      - name: Echo runner name
        run: |
          echo "$UID"
          ls /var/snap/microk8s/current/args/certs.d/docker.io/hosts.toml
