name: Push Event Tests

on:
  pull_request:

jobs:
  push-event-tests:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Echo runner name
        run: |
          echo "Hello, world again and again and again and again"
          echo "around the world around the world"
