name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: ubuntu-latest
    steps:
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.25/stable
          microk8s-addons: "storage dns rbac registry"
          juju-channel: 2.9/stable