name: Push Event Tests

on:
  push:

jobs:
  push-event-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Fix postgresql
        run: |
          sudo apt remove postgresql-client-common
          sudo apt install postgresql-client-common=238
          sudo apt install postgresql-common
      - name: setup user
        run: |
          sudo useradd -s /bin/bash -d /opt/stack -m stack
          sudo chmod +x /opt/stack
          echo "stack ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/stack
          sudo -u stack -i
      - name: install devstack
        run: |
          sudo apt update
          sudo apt install -y git
          git clone https://opendev.org/openstack/devstack
          cd devstack
          echo '[[local|localrc]]' > local.conf
          echo 'ADMIN_PASSWORD=secret' >> local.conf
          echo 'DATABASE_PASSWORD=$ADMIN_PASSWORD' >> local.conf
          echo 'RABBIT_PASSWORD=$ADMIN_PASSWORD' >> local.conf
          echo 'SERVICE_PASSWORD=$ADMIN_PASSWORD' >> local.conf
          ./stack.sh
      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
