name: CI
on: [push]
jobs:
  build:
    runs-on: ["ubuntu-22.04-arm"]
    steps:
      - name: print hardware resources
        run: |
          echo "Hardware resources:"
          echo "CPU: $(lscpu | grep 'Model name' | awk -F: '{print $2}')"
          echo "RAM: $(free -h | grep 'Mem' | awk '{print $2}')"
          echo "Disk: $(df -h / | grep '/' | awk '{print $2}')"